#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Droid.Resource", IsApplication=true)]

namespace Sample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.cameraBearing = global::Sample.Droid.Resource.Attribute.cameraBearing;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.cameraTargetLat = global::Sample.Droid.Resource.Attribute.cameraTargetLat;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.cameraTargetLng = global::Sample.Droid.Resource.Attribute.cameraTargetLng;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.cameraTilt = global::Sample.Droid.Resource.Attribute.cameraTilt;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.cameraZoom = global::Sample.Droid.Resource.Attribute.cameraZoom;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.circleCrop = global::Sample.Droid.Resource.Attribute.circleCrop;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.imageAspectRatio = global::Sample.Droid.Resource.Attribute.imageAspectRatio;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.imageAspectRatioAdjust = global::Sample.Droid.Resource.Attribute.imageAspectRatioAdjust;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.liteMode = global::Sample.Droid.Resource.Attribute.liteMode;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.mapType = global::Sample.Droid.Resource.Attribute.mapType;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiCompass = global::Sample.Droid.Resource.Attribute.uiCompass;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiMapToolbar = global::Sample.Droid.Resource.Attribute.uiMapToolbar;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiRotateGestures = global::Sample.Droid.Resource.Attribute.uiRotateGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiScrollGestures = global::Sample.Droid.Resource.Attribute.uiScrollGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiTiltGestures = global::Sample.Droid.Resource.Attribute.uiTiltGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiZoomControls = global::Sample.Droid.Resource.Attribute.uiZoomControls;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.uiZoomGestures = global::Sample.Droid.Resource.Attribute.uiZoomGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.useViewLifecycle = global::Sample.Droid.Resource.Attribute.useViewLifecycle;
			global::fivenine.UnifiedMaps.Droid.Resource.Attribute.zOrderOnTop = global::Sample.Droid.Resource.Attribute.zOrderOnTop;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_action_bar_splitter = global::Sample.Droid.Resource.Color.common_action_bar_splitter;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_dark_text_default = global::Sample.Droid.Resource.Color.common_signin_btn_dark_text_default;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_dark_text_disabled = global::Sample.Droid.Resource.Color.common_signin_btn_dark_text_disabled;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_dark_text_focused = global::Sample.Droid.Resource.Color.common_signin_btn_dark_text_focused;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_dark_text_pressed = global::Sample.Droid.Resource.Color.common_signin_btn_dark_text_pressed;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_default_background = global::Sample.Droid.Resource.Color.common_signin_btn_default_background;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_light_text_default = global::Sample.Droid.Resource.Color.common_signin_btn_light_text_default;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_light_text_disabled = global::Sample.Droid.Resource.Color.common_signin_btn_light_text_disabled;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_light_text_focused = global::Sample.Droid.Resource.Color.common_signin_btn_light_text_focused;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_light_text_pressed = global::Sample.Droid.Resource.Color.common_signin_btn_light_text_pressed;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_text_dark = global::Sample.Droid.Resource.Color.common_signin_btn_text_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Color.common_signin_btn_text_light = global::Sample.Droid.Resource.Color.common_signin_btn_text_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_full_open_on_phone = global::Sample.Droid.Resource.Drawable.common_full_open_on_phone;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_ic_googleplayservices = global::Sample.Droid.Resource.Drawable.common_ic_googleplayservices;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_disabled_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_disabled_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_disabled_focus_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_disabled_focus_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_disabled_focus_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_disabled_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_disabled_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_focus_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_focus_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_focus_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_focus_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_normal_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_normal_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_normal_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_normal_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_pressed_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_pressed_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_icon_pressed_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_icon_pressed_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_disabled_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_disabled_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_disabled_focus_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_disabled_focus_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_disabled_focus_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_disabled_focus_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_disabled_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_disabled_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_focus_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_focus_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_focus_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_focus_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_normal_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_normal_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_normal_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_normal_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_pressed_dark = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_pressed_dark;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.common_signin_btn_text_pressed_light = global::Sample.Droid.Resource.Drawable.common_signin_btn_text_pressed_light;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.ic_plusone_medium_off_client = global::Sample.Droid.Resource.Drawable.ic_plusone_medium_off_client;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.ic_plusone_small_off_client = global::Sample.Droid.Resource.Drawable.ic_plusone_small_off_client;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.ic_plusone_standard_off_client = global::Sample.Droid.Resource.Drawable.ic_plusone_standard_off_client;
			global::fivenine.UnifiedMaps.Droid.Resource.Drawable.ic_plusone_tall_off_client = global::Sample.Droid.Resource.Drawable.ic_plusone_tall_off_client;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.adjust_height = global::Sample.Droid.Resource.Id.adjust_height;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.adjust_width = global::Sample.Droid.Resource.Id.adjust_width;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.hybrid = global::Sample.Droid.Resource.Id.hybrid;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.none = global::Sample.Droid.Resource.Id.none;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.normal = global::Sample.Droid.Resource.Id.normal;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.satellite = global::Sample.Droid.Resource.Id.satellite;
			global::fivenine.UnifiedMaps.Droid.Resource.Id.terrain = global::Sample.Droid.Resource.Id.terrain;
			global::fivenine.UnifiedMaps.Droid.Resource.Integer.google_play_services_version = global::Sample.Droid.Resource.Integer.google_play_services_version;
			global::fivenine.UnifiedMaps.Droid.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::fivenine.UnifiedMaps.Droid.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
			global::fivenine.UnifiedMaps.Droid.Resource.String.auth_google_play_services_client_facebook_display_name = global::Sample.Droid.Resource.String.auth_google_play_services_client_facebook_display_name;
			global::fivenine.UnifiedMaps.Droid.Resource.String.auth_google_play_services_client_google_display_name = global::Sample.Droid.Resource.String.auth_google_play_services_client_google_display_name;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_android_wear_notification_needs_update_text = global::Sample.Droid.Resource.String.common_android_wear_notification_needs_update_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_android_wear_update_text = global::Sample.Droid.Resource.String.common_android_wear_update_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_android_wear_update_title = global::Sample.Droid.Resource.String.common_android_wear_update_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_api_unavailable_text = global::Sample.Droid.Resource.String.common_google_play_services_api_unavailable_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_enable_button = global::Sample.Droid.Resource.String.common_google_play_services_enable_button;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_enable_text = global::Sample.Droid.Resource.String.common_google_play_services_enable_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_enable_title = global::Sample.Droid.Resource.String.common_google_play_services_enable_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_error_notification_requested_by_msg = global::Sample.Droid.Resource.String.common_google_play_services_error_notification_requested_by_msg;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_install_button = global::Sample.Droid.Resource.String.common_google_play_services_install_button;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_install_text_phone = global::Sample.Droid.Resource.String.common_google_play_services_install_text_phone;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_install_text_tablet = global::Sample.Droid.Resource.String.common_google_play_services_install_text_tablet;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_install_title = global::Sample.Droid.Resource.String.common_google_play_services_install_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_invalid_account_text = global::Sample.Droid.Resource.String.common_google_play_services_invalid_account_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_invalid_account_title = global::Sample.Droid.Resource.String.common_google_play_services_invalid_account_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_needs_enabling_title = global::Sample.Droid.Resource.String.common_google_play_services_needs_enabling_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_network_error_text = global::Sample.Droid.Resource.String.common_google_play_services_network_error_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_network_error_title = global::Sample.Droid.Resource.String.common_google_play_services_network_error_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_notification_needs_update_title = global::Sample.Droid.Resource.String.common_google_play_services_notification_needs_update_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_notification_ticker = global::Sample.Droid.Resource.String.common_google_play_services_notification_ticker;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_sign_in_failed_text = global::Sample.Droid.Resource.String.common_google_play_services_sign_in_failed_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_sign_in_failed_title = global::Sample.Droid.Resource.String.common_google_play_services_sign_in_failed_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_unknown_issue = global::Sample.Droid.Resource.String.common_google_play_services_unknown_issue;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_unsupported_text = global::Sample.Droid.Resource.String.common_google_play_services_unsupported_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_unsupported_title = global::Sample.Droid.Resource.String.common_google_play_services_unsupported_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_update_button = global::Sample.Droid.Resource.String.common_google_play_services_update_button;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_update_text = global::Sample.Droid.Resource.String.common_google_play_services_update_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_update_title = global::Sample.Droid.Resource.String.common_google_play_services_update_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_updating_text = global::Sample.Droid.Resource.String.common_google_play_services_updating_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_google_play_services_updating_title = global::Sample.Droid.Resource.String.common_google_play_services_updating_title;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_open_on_phone = global::Sample.Droid.Resource.String.common_open_on_phone;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_signin_button_text = global::Sample.Droid.Resource.String.common_signin_button_text;
			global::fivenine.UnifiedMaps.Droid.Resource.String.common_signin_button_text_long = global::Sample.Droid.Resource.String.common_signin_button_text_long;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.LoadingImageView = global::Sample.Droid.Resource.Styleable.LoadingImageView;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.LoadingImageView_circleCrop = global::Sample.Droid.Resource.Styleable.LoadingImageView_circleCrop;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatio;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust = global::Sample.Droid.Resource.Styleable.LoadingImageView_imageAspectRatioAdjust;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs = global::Sample.Droid.Resource.Styleable.MapAttrs;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_cameraBearing = global::Sample.Droid.Resource.Styleable.MapAttrs_cameraBearing;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_cameraTargetLat = global::Sample.Droid.Resource.Styleable.MapAttrs_cameraTargetLat;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_cameraTargetLng = global::Sample.Droid.Resource.Styleable.MapAttrs_cameraTargetLng;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_cameraTilt = global::Sample.Droid.Resource.Styleable.MapAttrs_cameraTilt;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_cameraZoom = global::Sample.Droid.Resource.Styleable.MapAttrs_cameraZoom;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_liteMode = global::Sample.Droid.Resource.Styleable.MapAttrs_liteMode;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_mapType = global::Sample.Droid.Resource.Styleable.MapAttrs_mapType;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiCompass = global::Sample.Droid.Resource.Styleable.MapAttrs_uiCompass;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiMapToolbar = global::Sample.Droid.Resource.Styleable.MapAttrs_uiMapToolbar;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiRotateGestures = global::Sample.Droid.Resource.Styleable.MapAttrs_uiRotateGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiScrollGestures = global::Sample.Droid.Resource.Styleable.MapAttrs_uiScrollGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiTiltGestures = global::Sample.Droid.Resource.Styleable.MapAttrs_uiTiltGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiZoomControls = global::Sample.Droid.Resource.Styleable.MapAttrs_uiZoomControls;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_uiZoomGestures = global::Sample.Droid.Resource.Styleable.MapAttrs_uiZoomGestures;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_useViewLifecycle = global::Sample.Droid.Resource.Styleable.MapAttrs_useViewLifecycle;
			global::fivenine.UnifiedMaps.Droid.Resource.Styleable.MapAttrs_zOrderOnTop = global::Sample.Droid.Resource.Styleable.MapAttrs_zOrderOnTop;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::Sample.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::Sample.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int circleCrop = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatio = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int imageAspectRatioAdjust = 2130771984;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_ic_googleplayservices = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_signin_btn_icon_dark = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_disabled_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_light = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_focus_dark = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_light = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_normal_dark = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_light = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_pressed_dark = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_light = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_text_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_disabled_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_focus_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_focus_dark = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_normal_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_light = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_pressed_dark = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_light = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int ic_plusone_medium_off_client = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_plusone_small_off_client = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_standard_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_tall_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Icon = 2130837534;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int adjust_height = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int adjust_width = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int hybrid = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int myButton = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int none = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int normal = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int satellite = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int terrain = 2131165188;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040025
			public const int app_name = 2130968613;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f040024
			public const int hello = 2130968612;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
